name = "foodandtravel"
description = "Food and Travel is a travel vlog project dedicated to sharing unique culinary and travel experiences from around the world."

[project]
id = 3
name = "foodandtravel"
repository = "foodandtravel"
description = "food and travel"
created_at = "2025-05-29T16:12:15.062Z"
updated_at = "2025-05-29T16:12:15.062Z"
